


INSERT INTO plan(codigo,acciones_codigo,tipo_equipo_codigo,nombre,descripcion)VALUES
('CODPLA001','CODACC004','CODTEQ003','CIERRE CARRIL DERECHO','Se cierra carril derecho')
('CODPLA002','CODACC004','CODTEQ003','CIERRE CARRIL DERECHO Y CENTRAL','Se cierra carril derecho y central') 
('CODPLA003','CODACC004','CODTEQ003','CIERRE CARRIL IZQUIERDO','Se cierra carril izquierdo')
('CODPLA004','CODACC004','CODTEQ003','CIERRE CARRIL IZQUIERDO Y CENTRAL','Se cierra carril izquierdo y central')
('CODPLA005','CODACC004','CODTEQ003','RESTABLECIMIENTO','Se restablece PMB')
('CODPLA006','CODACC004','CODTEQ003','VEHICULO CIRCULACION LENTA','Vehiculo de circulacion lenta')
('CODPLA007','CODACC004','CODTEQ003','CONGESTION VEHICULAR','Congestion vehicular')
('CODPLA008','CODACC004','CODTEQ003','LLUVIA - VIA RESBALADIZA','Lluvia - via resbaladiz')
('CODPLA009','CODACC004','CODTEQ003','INCENDIO EN EL TUNEL','Incendio en el tune')
('CODPLA010','CODACC004','CODTEQ003','CARGA ANCHA','Carga ancha')
('CODPLA011','CODACC004','CODTEQ003','ACCIDENTE VEHICULAR','Accidente vehicula')
('CODPLA012','CODACC004','CODTEQ003','MANTENIMIENTO EN EL TUNEL','Mantenimiento en el tune')
